### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

### ISSUE THREAD

**Issue by Maras0830** [MD3XTER/Twitch-Farmer#1]
Hello,

I got the error after run command: python3 Twitch-Farmer.py: 

`FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'`

how to resolve it?

**Comment by MD3XTER** [comment]
if you are on windows, you should put your chromedriver path in environments-path and it will work,
http://splinter.readthedocs.io/en/0.1/setup-chrome.html

**Comment by Maras0830** [comment]
how to do it on macOs?

**Comment by MD3XTER** [comment]
http://splinter.readthedocs.io/en/0.1/setup-chrome.html#linux-and-mac-os-x

**Comment by Maras0830** [comment]
thanks a lot!
