### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'username'

### ISSUE THREAD

**Issue by razzac** [MD3XTER/Twitch-Farmer#10]
Traceback (most recent call last):
  File "twitch_farmer.py", line 254, in <module>
    main()
  File "twitch_farmer.py", line 126, in main
    username_rows = accounts_csv.username
  File "C:\Python3\lib\site-packages\pandas\core\generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'username'

**Comment by MD3XTER** [comment]
@razzac It seems like **pandas** can't find the column **username** in _accounts.csv_ file.

Can you open the _accounts.csv_ file in a text editor, copy the first row(**header**) and paste it here?

I guess you opened the _accounts.csv_ in **Excel** and it changed the delimiter from "**,**" to "**;**"
