### ISSUE TITLE
I am getting a NameError when I type in the name of the channel I want it to follow

### ISSUE THREAD

**Issue by KevinJones20** [MD3XTER/Twitch-Farmer#11]
What channel should I follow? : Traceback (most recent call last):
  File "twitch_farmer.py", line 254, in <module>
    main()
  File "twitch_farmer.py", line 116, in main
    follow_channel_name = input("What channel should I follow? : ")
  File "<string>", line 1, in <module>
NameError: name 'theirchannelname' is not defined

**Comment by MD3XTER** [comment]
I am not sure what's the problem. I have tested on my side it works. Make sure you are running the specified python version.

Also, I think, it may be the environment you are running it from. What are you using, terminal and if so, which?

**Comment by KevinJones20** [comment]
Ive tried to run it through git, python, cmd, whatever I use I get the same error, I haven't messed with the code whatsoever so I am not sure why it says it isn't defined.

**Comment by KevinJones20** [comment]
I'm also using Windows 10

**Comment by KevinJones20** [comment]
Also it doesn't let me run it by typing 'python3' , I have to say python

**Comment by KevinJones20** [comment]
Yeah you are right, it is still running 2.7 even though I've tried running it from python 3

**Comment by MD3XTER** [comment]
Did you solve the problem?

**Comment by KevinJones20** [comment]
Well I decided to uninstall 2.7 completely from my computer, its now running 3.7 through gitbash, but now I am getting this error
$ python3 twitch_farmer.py
Traceback (most recent call last):
  File "twitch_farmer.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
But when I type the pip install selenium pandas line, it returns nothing, and I've already confirmed my PATHs and pip install went well, so I'm not sure what the issue is now

**Comment by MD3XTER** [comment]
Sorry, it's my fault, I should have mentioned that you should use `pip3` for **python 3**.

I will update the README.

**Comment by KevinJones20** [comment]
Ahhh gotcha, yeah that worked, it's installed, now I can run it and it does work but I get


Traceback (most recent call last):
  File "twitch_farmer.py", line 254, in <module>
    main()
  File "twitch_farmer.py", line 126, in main
    username_rows = accounts_csv.username
  File "F:\Python37\lib\site-packages\pandas\core\generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'username'


I entered a real username and password for a twitch account, do you know what is causing this error?

**Comment by MD3XTER** [comment]
It seems it has to do with the .csv file. It can't find the column **username**.

Make sure your file looks like this: https://github.com/MD3XTER/Twitch-Farmer#usage

**Comment by KevinJones20** [comment]
Okay, I've gotten it working to the point where it's repeatedly opening chrome but not loading the page correctly/continually closing

**Comment by MD3XTER** [comment]
It means that the proxies are not good

**Comment by KevinJones20** [comment]
It keeps saying time expired changing proxy, even after I changed them to working ones

**Comment by MD3XTER** [comment]
Are you sure the proxy is working? I have tested it with some proxies and it worked. What type of proxy are you using?

I will also have a deeper look tomorrow.

**Comment by KevinJones20** [comment]
I'm just using proxies from an online proxy list so it might not be the best source

**Comment by MD3XTER** [comment]
Yes, you have to buy unused proxies so the bot will work properly.
