### ISSUE TITLE
problem...help?

### ISSUE THREAD

**Issue by JeroenV99** [MD3XTER/Twitch-Farmer#15]
when i run the bot it is only a strokes of errors
![image](https://user-images.githubusercontent.com/35964877/54530497-32014c00-4983-11e9-98fc-294dfaf0fed8.png) how can i fix it?

**Comment by MD3XTER** [comment]
Which platform are you running it on?

**Comment by JeroenV99** [comment]
Parrot Linux

**Comment by MD3XTER** [comment]
64 or 32?

**Comment by JeroenV99** [comment]
64 bit

**Comment by MD3XTER** [comment]
hmm, it seems like the script can't find the chromedriver or the chromedriver is not compatible with your system. Unfortunately I don't have a Linux system near me so I can't test it. You can try to run chromdriver from the "drivers" folder and see if it opens.

**Comment by JeroenV99** [comment]
do you have a Installation guide for windows?

**Comment by MD3XTER** [comment]
There is not specific guide, as the bot should detect your system automaticaly and use the right chromedriver for your system.

**Comment by JeroenV99** [comment]
but how do i can install the chromedriver, i cant find it on google

**Comment by MD3XTER** [comment]
Chromedrivers are already in your bot folder "drivers"

**Comment by JeroenV99** [comment]
but how do i install it?

**Comment by MD3XTER** [comment]
You don't have to install it, just run it

**Comment by JeroenV99** [comment]
![image](https://user-images.githubusercontent.com/35964877/54542638-7c42f700-499c-11e9-82d3-4b5d7b60f317.png)

**Comment by JeroenV99** [comment]
![image](https://user-images.githubusercontent.com/35964877/54542658-8664f580-499c-11e9-950f-27446e763c53.png)

**Comment by MD3XTER** [comment]
It seems like you have used all your proxies. Also, can you reply next time to github issue instead of email?

Kind regards,

Andrei Zgîrvaci
Front-End/Mobile Developer | Bravrr LLC 
M: +31 618 255 813 <tel:+31 618 255 813>
E: zgirvaciandrei@gmail.com <mailto:zgirvaciandrei@gmail.com>

**Comment by andrei-zgirvaci** [comment]
I will close it for now. Tell me if you have any updates.
