### ISSUE TITLE
subs prime

### ISSUE THREAD

**Issue by alanhoffer** [MD3XTER/Twitch-Farmer#17]
if i do this can work with twitch subs prime?

```
        sub_button = driver.find_element_by_xpath(
            get_page_element("sub_button"))

        sub_button.click()

        sleep(5)

        subprime_button = driver.find_element_by_xpath(
            get_page_element("subprime_button"))

        subprime_button.click()

        # wait for request
        sleep(5)

```

    "subprime_button": {
        "type": "xPath",
        "value": "//button[@data-a-target='subscribe-with-prime-button']"
    },
    "sub_button": {
        "type": "xPath",
        "value": "//button[@data-a-target='subscribe-button']"
    },

**Comment by andrei-zgirvaci** [comment]
I didn't test if it works, but you are on the right path. I guess subscribing will be harder to accomplish as you need to do additional steps in order to subscribe.
