### ISSUE TITLE
where i can get proxys?

### ISSUE THREAD

**Issue by alanhoffer** [MD3XTER/Twitch-Farmer#18]
i cant get nice proxys and 1 follower XD where i can get proxys

**Comment by andrei-zgirvaci** [comment]
I haven't buy proxies. You can find a lot of good websites on google. Make sure to check the reviews.

**Comment by alanhoffer** [comment]
maybe the bot works better working with sessionbox?

**Comment by alanhoffer** [comment]
i cant get 1 followed work

**Comment by andrei-zgirvaci** [comment]
I don't know what is sessionbox

**Comment by alanhoffer** [comment]
open new twitch window with new session and u can save 50 sessions and open in the same time

**Comment by andrei-zgirvaci** [comment]
No, haven't heard of that
