### ISSUE TITLE
Hi @andrei-zgirvaci  can you share your email

### ISSUE THREAD

**Issue by 2div** [MD3XTER/Twitch-Farmer#37]
Hi @andrei-zgirvaci  

i want to contact you.

can you please share your email address , thanks

**Comment by andrei-zgirvaci** [comment]
@2div you can find my email address on my profile page on GitHub. :)

**Comment by liezahub** [comment]
hi your trying to contact me is this right.On 4 Jul 2023, at 15:58, Andrei Zgîrvaci ***@***.***> wrote:﻿
@2div you can find my email address on my profile page on GitHub. :)

**Comment by 2div** [comment]
I searched I didn't find it.

**Comment by liezahub** [comment]
you can contact me with this email what are you requiring from me.On 5 Jul 2023, at 14:26, 2div ***@***.***> wrote:﻿
I searched I didn't find it.

**Comment by andrei-zgirvaci** [comment]
@liezahub Give me your email, I will email you!

**Comment by liezahub** [comment]
***@***.*** 5 Jul 2023, at 14:36, Andrei Zgîrvaci ***@***.***> wrote:﻿
@liezahub Give me your email, I will email you!

**Comment by andrei-zgirvaci** [comment]
@liezahub please don't use the email to reply to this issue. Comment directly on GitHub instead! https://github.com/andrei-zgirvaci/Twitch-Farmer/issues/37

**Comment by liezahub** [comment]
hello

**Comment by andrei-zgirvaci** [comment]
@liezahub give me your email so I can email you.

**Comment by liezahub** [comment]
liamelsdon@icloud.com
