### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by henry10222** [MD3XTER/Twitch-Farmer#5]
After starting it with cmd I got this error.
 
 
File "Twitch-Farmer.py", line 166
   print ("Bot Stopped!!!")
                          ^
IndentationError: unindent does not match any outer indentation level

**Comment by MD3XTER** [comment]
Thank you, It should be fixed now

**Comment by henry10222** [comment]
Got a problem with Login.
He start the Chrome Browser but there is a captcha and I cant get it.

**Comment by MD3XTER** [comment]
Try to use different proxy, usually if you use a good proxy, you shouldn't have any problems

**Comment by MD3XTER** [comment]
@henry10222 It's been a while since your issue but I have just released the 2.0 version, have a look and see if you have that issue anymore.
