### ISSUE TITLE
 Just the login screen

### ISSUE THREAD

**Issue by caiomcs** [MD3XTER/Twitch-Farmer#6]
When it starts the code it loads correctly to the login screen of the twitch, but does not put the username nor the password, then gives the time and goes to the next proxy ip

what channel should i follow?: test
using proxy: ip:port

using username: test
using password: test

------------------------------------------- 

Time expired, changing proxy!!!(1)

**Comment by MD3XTER** [comment]
Hey, thanks for the noticing that!

I just [commited](https://github.com/MD3XTER/Twitch-Farmer/commit/01693fcf7ee121bee1201f217ace3ded05ea5945) a fix for this issue, now it should work as expected :)

p.s also I have included chromedriver in a local folder so you don't need to install it again.

Hope it helps, let me know if you have any other issues!

**Comment by caiomcs** [comment]
You can do something wrong, even doing the same thing as before, but when I start the code it works until the channel insertion part, and when I press enter it goes straight to the: print ("Bot Stopped !!!")

user@server:~/Twitch-Farmer$ python3 Twitch-Farmer.py 
what channel should i follow?: test
Bot Stopped!!!

And thanks for the help so fast.

**Comment by MD3XTER** [comment]
Tomorrow, I will push the new version of the script 2.0, which has more futures and should be easier to use ;)

**Comment by caiomcs** [comment]
Nice! I'm here for anything, thank you in advance

**Comment by MD3XTER** [comment]
@caiomcs I have just released the 2.0 version #7. Have a look at the README, I tried to make it as understandable as possible.

Because it's a new version, I expect some issues, so don't hesitate to open new ones if you encounter any problems.

I will close this issue, as it's no more relevant to the current version.
