### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by caiomcs** [MD3XTER/Twitch-Farmer#8]
Good afternoon, sorry for the inconvenience, but I put it according to the "README" and when I start the code it responds with this error:

user@server:~/Twitch-Farmer$ python3 twitch_farmer.py 
What channel should I follow? : test
Traceback (most recent call last):
  File "twitch_farmer.py", line 244, in <module>
    main()
  File "twitch_farmer.py", line 120, in main
    with open(get_full_path("/page_elements.json")) as page_elements_file:
TypeError: invalid file: PosixPath('/home/user/Twitch-Farmer/page_elements.json')

**Comment by MD3XTER** [comment]
On what OS are you?

**Comment by caiomcs** [comment]
Linux/Ubunto 16.04.5 LTS

**Comment by MD3XTER** [comment]
@caiomcs what version of python are you running it with?

**Comment by caiomcs** [comment]
Sorry for the delay, I saw that it was in the wrong version, so I updated it and I put the code to run, the only problem I ran more than 50 ip proxy and none opened, being tested by the browser every proxy and loaded normal .., I do not know if I am doing it wrong or is there any incompatibility

**Comment by MD3XTER** [comment]
@caiomcs what type of proxies are they? SOCKS5?

**Comment by caiomcs** [comment]
I was not sure if it was "SOCKS5", so I just got 5 to test and when I got the code, but I did not load the page. different from the first time I used the code, which I loaded but did not log ..

**Comment by MD3XTER** [comment]
@caiomcs I just committed a fix [f04fd54](https://github.com/MD3XTER/Twitch-Farmer/commit/f04fd5454914598761eab1ae402850791dd8a545), it should be fixed now.

I will close this issue because you fixed it.
